remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Portfólio de Data Science – Welington Nogueira"
description: "Projetos em Python, Machine Learning e Estatística Aplicada"
